P19:
- chef/cook
- waiter/server
- waitress/server
- engineer
- manager
- pilot
- flight attendant
- hairdresser
- manicurist
- tailor
- 'child day-care worker'
- homemaker
- travel agent
- salesperson
- stock clerk
- store owner/shopkeeper