P3:
  - year
  - season
  - month
  - week
  - weekend
  - day
  - Sunday
  - Monday
  - Tuesday
  - Wednesday
  - Thursday
  - Friday
  - Saturday
  - January
  - February
  - March
  - April
  - May
  - June
  - July
  - August
  - September
  - October
  - November
  - December
  - spring
  - summer
  - fall/autumn
  - winter
  - January 1, 2014/January first, two thousand fourteen
P9:
  - white
  - black
  - red
  - blue
  - yellow
  - green
  - orange
  - purple
  - brown
  - beige
  - silver
  - gold
  - gray
  - navy blue
  - sky blue
  - light green
  - dark green
  - khaki
  - violet
  - ivory
  - colorful
  - transparent
P10:
  - good
  - bad
  - young
  - old
  - tall
  - short
  - neat
  - messy
  - large/big
  - small/little
  - fast/quick
  - slow
  - heavy/fat
  - thin/slim/skinny
  - rich/wealthy
  - poor
  - lovely/pretty/beautiful
  - ugly
  - handsome
  - ugly
  - noisy/loud
  - quiet
  - honest
  - dishonest
  - friendly/kind
  - mean
  - healthy
  - unhealthy
  - naughty
  - 'well-behaved'
  - loyal
  - helpful
  - lucky
  - funny
  - great
  - cool
P11:
  - new
  - old
  - hot
  - cold
  - long
  - short
  - clean
  - dirty
  - easy
  - difficult/hard
  - heavy
  - light
  - open
  - closed
  - full
  - empty
  - fancy
  - plain
  - straight
  - crooked
  - straight
  - curly
  - wide
  - narrow
  - thick
  - thin
  - dark
  - light
  - high
  - low
  - loose
  - tight
  - comfortable
  - uncomfortable
  - shiny
  - dull
  - smooth
  - rough
  - soft
  - hard
  - sharp
  - dull
  - wet
  - dry
P12-P13:
  - full
  - hungry
  - thirsty
  - tired/exhausted
  - sleepy
  - awake
  - sick/ill
  - healthy
  - happy
  - sad/unhappy
  - excited
  - upset
  - angry/mad
  - surprised
  - shocked
  - jealous
  - nervous
  - scared/afraid
  - worried
  - curious
  - confused
  - brave
  - proud
  - embarrassed
  - disappointed
  - ashamed
  - frustrated
  - annoyed
  - disgusted
  - bored
  - lonely
  - homesick
P14:
  - age
  - young
  - 'middle-aged'
  - old/elderly
  - height
  - tall
  - average height
  - short
  - weight
  - heavy/fat
  - average weight
  - thin/slim
  - skinny
  - pregnant
  - shoulder length (hair)
  - short (hair)
  - straight (hair)
  - wavy (hair)
  - curly (hair)
  - black (hair)
  - brown (hair)
  - blonde (hair)/blond (hair)
  - red (hair)
  - gray (hair)
  - bald
  - beard
  - mustache
P15:
  - sex/gender
  - date of birth
  - place of birth
  - age
  - name
  - first name/given name
  - middle name/given name
  - last name/family name/surname
  - initials
  - address
  - street number
  - street
  - apartment number
  - city
  - state
  - province
  - country
  - zip code/postal code
  - area code
  - telephone number/phone number
  - cell phone number
  - email address/e-mail address
P16:
  - parents
  - monther/mom
  - father/dad
P17:
  - baby/infant
  - child/children
  - teenager
  - adult
  - senior citizen/elderly person
  - girl
  - boy
  - woman/women
  - man/men
  - neighbor
  - friend
  - classmate
  - teammate
  - captain/team leader
  - coach
  - teacher
  - coworker
  - partner
  - supervisor
  - boss
P18:
  - actor
  - actress
  - dancer
  - singer
  - artist
  - teacher/instructor
  - principal
  - firefighter
  - police officer
  - soldier
  - doctor
  - nurse
  - veterinarian/vet
  - farmer
  - fisher
  - mail carrier/letter carrier
  - postal worker
  - driver
  - bud driver
  - taxi driver
  - housekeeper
  - babysitter
P19:
  - chef/cook
  - waiter/server
  - waitress/server
  - engineer
  - manager
  - pilot
  - flight attendant
  - hairdresser
  - manicurist
  - tailor
  - 'child day-care worker'
  - homemaker
  - travel agent
  - salesperson
  - stock clerk
  - store owner/shopkeeper
  - baker
  - butcher
  - 'food-service worker'
  - florist
  - cashier