P3:
  - year
  - season
  - month
  - week
  - weekend
  - day
  - Sunday
  - Monday
  - Tuesday
  - Wednesday
  - Thursday
  - Friday
  - Saturday
  - January
  - February
  - March
  - April
  - May
  - June
  - July
  - August
  - September
  - October
  - November
  - December
  - spring
  - summer
  - fall/autumn
  - winter
  - January 1, 2014/January first, two thousand fourteen
P4:
  - morning
  - afternoon
  - evening
  - night
  - yesterday
  - today
  - tomorrow
  - yesterday morning
  - yesterday afternoon
  - yesterday evening
  - last night
  - this morning
  - this afternoon
  - this evening
  - tonight
  - tomorrow morning
  - tomorrow afternoon
  - tomorrow evening
  - tomorrow night
  - last week
  - this week
  - next week
  - once a week
  - twice a week
  - three times a week
  - every day
  - early
  - late
  - on time
P5:
  - height
  - width
  - depth
  - length
  - inch
  - foot/feet
  - yard
  - centimeter
  - meter
  - mile
  - kilometer
  - ounce
  - pound
  - ton
  - gram
  - kilogram
  - metric ton/tonne
  - cup
  - pint
  - quart
  - gallon
  - milliliter
  - liter
P8:
  - dot
  - dotted line
  - line
  - circle
  - oval
  - pie
  - triangle
  - square
  - rectangle
  - pentagon
  - hexagon
  - octagon
  - star
  - heart
  - diamond
  - sphere
  - cylinder
  - cone
  - pyramid
  - cube
P9:
  - white
  - black
  - red
  - blue
  - yellow
  - green
  - orange
  - purple
  - brown
  - beige
  - silver
  - gold
  - gray
  - navy blue
  - sky blue
  - light green
  - dark green
  - khaki
  - violet
  - ivory
  - colorful
  - transparent
P10:
  - good
  - bad
  - young
  - old
  - tall
  - short
  - neat
  - messy
  - large/big
  - small/little
  - fast/quick
  - slow
  - heavy/fat
  - thin/slim/skinny
  - rich/wealthy
  - poor
  - lovely/pretty/beautiful
  - ugly
  - handsome
  - ugly
  - noisy/loud
  - quiet
  - honest
  - dishonest
  - friendly/kind
  - mean
  - healthy
  - unhealthy
  - naughty
  - 'well-behaved'
  - loyal
  - helpful
  - lucky
  - funny
  - great
  - cool
P11:
  - new
  - old
  - hot
  - cold
  - long
  - short
  - clean
  - dirty
  - easy
  - difficult/hard
  - heavy
  - light
  - open
  - closed
  - full
  - empty
  - fancy
  - plain
  - straight
  - crooked
  - straight
  - curly
  - wide
  - narrow
  - thick
  - thin
  - dark
  - light
  - high
  - low
  - loose
  - tight
  - comfortable
  - uncomfortable
  - shiny
  - dull
  - smooth
  - rough
  - soft
  - hard
  - sharp
  - dull
  - wet
  - dry
P12-P13:
  - full
  - hungry
  - thirsty
  - tired/exhausted
  - sleepy
  - awake
  - sick/ill
  - healthy
  - happy
  - sad/unhappy
  - excited
  - upset
  - angry/mad
  - surprised
  - shocked
  - jealous
  - nervous
  - scared/afraid
  - worried
  - curious
  - confused
  - brave
  - proud
  - embarrassed
  - disappointed
  - ashamed
  - frustrated
  - annoyed
  - disgusted
  - bored
  - lonely
  - homesick
P14:
  - age
  - young
  - 'middle-aged'
  - old/elderly
  - height
  - tall
  - average height
  - short
  - weight
  - heavy/fat
  - average weight
  - thin/slim
  - skinny
  - pregnant
  - shoulder length (hair)
  - short (hair)
  - straight (hair)
  - wavy (hair)
  - curly (hair)
  - black (hair)
  - brown (hair)
  - blonde (hair)/blond (hair)
  - red (hair)
  - gray (hair)
  - bald
  - beard
  - mustache
P15:
  - sex/gender
  - date of birth
  - place of birth
  - age
  - name
  - first name/given name
  - middle name/given name
  - last name/family name/surname
  - initials
  - address
  - street number
  - street
  - apartment number
  - city
  - state
  - province
  - country
  - zip code/postal code
  - area code
  - telephone number/phone number
  - cell phone number
  - email address/e-mail address
P16:
  - parents
  - monther/mom
  - father/dad
P17:
  - baby/infant
  - child/children
  - teenager
  - adult
  - senior citizen/elderly person
  - girl
  - boy
  - woman/women
  - man/men
  - neighbor
  - friend
  - classmate
  - teammate
  - captain/team leader
  - coach
  - teacher
  - coworker
  - partner
  - supervisor
  - boss
P18:
  - actor
  - actress
  - dancer
  - singer
  - artist
  - teacher/instructor
  - principal
  - firefighter
  - police officer
  - soldier
  - doctor
  - nurse
  - veterinarian/vet
  - farmer
  - fisher
  - mail carrier/letter carrier
  - postal worker
  - driver
  - bud driver
  - taxi driver
  - housekeeper
  - babysitter
P19:
  - chef/cook
  - waiter/server
  - waitress/server
  - engineer
  - manager
  - pilot
  - flight attendant
  - hairdresser
  - manicurist
  - tailor
  - 'child day-care worker'
  - homemaker
  - travel agent
  - salesperson
  - stock clerk
  - store owner/shopkeeper
  - baker
  - butcher
  - 'food-service worker'
  - florist
  - cashier
P20:
  - designer
  - translator/interpreter
  - journalist
  - reporter
  - writer/author
  - musician
  - painter
  - photographer
  - professor
  - 'health-care aide/health-care attendant'
  - medical assistant/physician assistant
  - sailor
  - bricklayer/mason
  - carpenter
  - construction worker
  - custodian/janitor
  - delivery person
  - dockworker
  - factory worker
  - machine operator
P21:
  - mechanic
  - mover
  - repairperson
  - sanitation worker/trash collector
  - security guard
  - welder
  - businesswoman
  - businessman
  - receptionist
  - secretary
  - accountant
  - architect
  - computer software engineer
  - judge
  - lawyer
  - pharmacist
  - scientist
  - astronaut
P22-P23:
  - play cards
  - (deck of) cards
  - club
  - diamond
  - heart
  - spade
  - play board games
  - Chess
  - Checkers
  - Backgammon
  - Monopoly
  - dice
  - Scrabble
  - go online/surf the Net/browse the web
  - web browser
  - web address/URL/link
  - photography
  - camera
  - lens
  - flash
  - memory disk
  - battery
  - astronomy
  - telescope
  - sew
  - needle
  - thread
  - knit
  - knitting needles
  - yarn
  - paint
  - paintbrush
  - canvas
  - paint
  - draw
  - sketch book
  - colored pencil
  - drawing pencil
  - do woodworking
  - do origami
  - make pottery
  - collect stamps
  - collect coins
  - build models
  - model kit
  - glue
  - go bird-watching
  - binoculars
P24:
  - wash my hair
  - dry my hair
  - comb my hair
  - brush my hair
  - style my hair
  - wash my hair
  - shave
  - brush my teeth
  - floss my teeth
  - gargle
  - take a bath/bathe
  - take a shower
  - shave my armpits
  - put on deodorant
  - put on lotion/moisturize
  - put on makeup
  - do my nails
  - shave my legs
  - polish my shoes
P25:
  - comb
  - hairbrush
  - hairspray
  - styling gel
  - hair dryer/blow dryer
  - mouthwash
  - dental floss
  - makeup
  - eye shadow
  - mascara
  - blush
  - lipstick
  - moisturizer
  - sunscreen
  - body lotion
  - hand lotion
  - deodorant
  - cologne
  - perfume
  - nail clipper
  - nail polish
  - razor
  - electric shaver
P26-27:
  - head
  - hair
  - forehead
  - face
  - eye
  - eyebrow
  - eyelid
  - eyelashes
  - ear
  - cheek
  - nose
  - mouth
  - lips
  - tooth/teeth
  - tongue
  - jaw
  - chin
  - neck
  - shoulder
  - arm
  - elbow
  - wrist
  - hand
  - palm
  - thumb
  - finger
  - fingernail
  - knuckle
  - chest
  - abdomen
  - belly button
  - waist
  - back
  - hip
  - buttocks/bottom
  - leg
  - thigh
  - knee
  - calf
  - shin
  - foot/feet
  - ankle
  - heel
  - toe
  - toenail
  - skin
  - brain
  - throat
  - esophagus
  - lung
  - heart
  - liver
  - gallbladder
  - stomach
  - large intestine
  - small intestine
  - pacreas
  - kidney
  - bladder
  - vein
  - muscle
  - bone
  - skull
  - skeleton
  - ribcage
  - spine
P43:
  - ceiling
  - walls
  - floor
  - picture
  - photograph/photo
  - frame
  - flowers
  - vase
  - fireplace
  - bookshelf/bookcase
  - entertainment center
  - television/TV
  - DVD player
  - speakers
  - stereo system
  - remote control
  - air conditioner
  - fan
  - window
  - drapes/curtains
  - sofa/couch
  - cushions
  - pillow
  - end table
  - lamp
  - telephone/phone
  - carpet
  - rug/area rug
  - coffee table
  - stairs/staircase
P76:
  - bakery
  - coffee shop/cafe
  - pizza shop
  - ice cream shop
  - candy store
  - delicatessen/deli
  - fast-food restaurant
  - restaurant
  - stationery shop
  - book store
  - music store
  - flower shop
  - toy store
  - pet shop/pet store
  - car dealership
  - real estate agency
P77:
  - barber shop
  - hair salon
  - nail salon
  - jewelry store
  - clothing store
  - shoe store
  - department store
  - shopping mail
  - convenience store
  - grocery store
  - fruit shop
  - supermarket
  - health club/gym
  - movie theater/cinema
  - furniture store
  - dry cleaners/cleaners
P136(Africa):
  - Algeria
  - Central African Republic
  - Egypt
  - Ethiopia
  - Ghana
  - Kenya
  - Libya
  - Madagascar
  - Morocco
  - Nigeria
  - South Africa
P136(Asia):
  - Afghanistan
  - Cambodia
  - China
  - India
  - Indonesia
  - Iran
  - Irag
  - Israel
  - Japan
  - Malaysia
  - North Korea
  - Pakistan
  - Philippines
  - Russia
  - Saudi Arabia
  - Singapore
  - South Korea
  - Thailand
  - Vietnam